# Site settings
title: The Waterloo Investor
email: wtrlnvstr@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://wtrlnvstr.github.io"
# twitter_username: jekyllrb
github_username: wtrlnvstr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

